services:
  phpmyadmin:
    container_name: sneakers-phpmyadmin
    image: phpmyadmin
    environment:
      - PMA_HOST=sneakers-database
    ports:
      - "6060:80"
    networks:
      - sneakers-network
 
  database:
    container_name: sneakers-database
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=teo
    ports: 
      - "3306:3306"
    networks:
      - sneakers-network
 
networks:
  sneakers-network: